### ISSUE TITLE
Ask for information about the experiment_id for downloading the expression energy for an ISH experiment

### ISSUE THREAD

**Issue by ZhenyaoYe** [abeaucha/MouseHumanTranscriptomicSimilarity#9]
Hi Antoine Beauchamp,

My name is Zhenyao Ye. I am really interested in your one of the papers (Whole-brain comparison of rodent and human brains using spatial transcriptomics). And thanks for publicly sharing your codes for downloading/processing the data used in your study. 

For your download_AMBA.py, the experiment_id is required for downloading adult mouse whole-brain in-situ hybridization expression data sets. I would like to confirm the source of experiment_ids (http://download.alleninstitute.org/informatics-archive/october-2014/mouse_expression/Accessing_October_2014_expression_data.pdf, the mouse_expression_data_sets.csv highlighted in the below image) with you and am wondering if you used data_set_id included in the file to be experiment_ids. If so, there are a total of 25899 datasets for all coronal and sagittal sets, which are different from "The result of this pre-processing pipeline was a gene-by-voxel expression matrix with 3958 genes and 61315 voxels for the coronal data set and a matrix with 3619 genes and 26317 voxels for the sagittal data set." stated in your paper. Any suggestions are appreciated! 
![image](https://user-images.githubusercontent.com/42884609/191800759-0101360e-4ee0-43c0-ac56-a1bb7730e401.png)

Best regards,
Zhenyao

**Comment by abeaucha** [comment]
Hi Zhenyao, 

Great to hear you're interested in this project! I am not using the "mouse_expression-data_sets.csv" file you mentioned, though it appears to refer to the same data set. Rather than separating the coronal and sagittal data sets, that file combines them together, which you can see by examining the "plane_of_section" column. 

In our pipeline, we pulled the metadata directly from the Allen Institute API. The relevant function is `fetch_metadata()` in the script "download_AMBA.py". The "experiment_id" column is assigned as part of this API query is written out to .csv. Use `dataset = 'coronal'` or `dataset = 'sagittal'` when calling `fetch_metadata()` to specify the dataset you want.

**Comment by ZhenyaoYe** [comment]
Hi Antoine, 

Thank you so much for your responses. That helps a lot! 

Best regards,
Zhenyao

**Comment by abeaucha** [comment]
Happy to help!
